apiVersion: v1
kind: Secret
metadata:
  name: gitrack-config
  labels:
    app: gitrack
type: Opaque
stringData:
  GITHUB_TOKEN: ""
  LLM_PROVIDER: "ollama"
  ANTHROPIC_API_KEY: ""
  GROQ_API_KEY: ""
  OLLAMA_HOST: ""
  OLLAMA_MODEL: "llama3"
  VERTEX_PROJECT_ID: ""
  VERTEX_REGION: "us-east5"
  VERTEX_MODEL: ""
  VERTEX_SA_KEY: ""
  SETTINGS_ENCRYPTION_KEY: "fc8c30fe1e269fc889d9aee56e1bb3a58389bf27ade157f7aa3dfc487e41345a"
